In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4])

In [3]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s1.values

array([1, 2, 3, 4])

In [5]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
s2 = pd.Series(np.arange(10))

In [7]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [8]:
s3 = pd.Series({"1":1,"2":2,"3":3})

In [9]:
s3

1    1
2    2
3    3
dtype: int64

In [10]:
s3.values

array([1, 2, 3])

In [11]:
s3.index

Index(['1', '2', '3'], dtype='object')

In [12]:
s4 = pd.Series([1,2,3,4],index=['A','B','C','D'])

In [13]:
s4.values

array([1, 2, 3, 4])

In [14]:
s4.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [15]:
s4["A"]

1

In [16]:
s4[s4>2]

C    3
D    4
dtype: int64

In [17]:
s4.to_dict()

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [22]:
s5=pd.Series(s4.to_dict())

In [23]:
s5

A    1
B    2
C    3
D    4
dtype: int64

In [24]:
index_1 = ["A","B","C","D","E"]
s6 = pd.Series(s5,index=index_1)

In [25]:
s6

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [26]:
pd.isnull(s6)

A    False
B    False
C    False
D    False
E     True
dtype: bool

In [28]:
pd.notnull(s6)

A     True
B     True
C     True
D     True
E    False
dtype: bool

In [29]:
s6.name='demo'

In [30]:
s6

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
Name: demo, dtype: float64

In [31]:
s6.index.name='index value'

In [32]:
s6

index value
A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
Name: demo, dtype: float64