In [1]:
import pandas as pd
import numpy as np
import scipy.stats as ss
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
    #特征选择
    df=pd.DataFrame({"A":ss.norm.rvs(size=10),"B":ss.norm.rvs(size=10),\
                     "C":ss.norm.rvs(size=10),"D":np.random.randint(low=0,high=2,size=10)})

In [3]:
df

A         B         C  D
0 -0.441526 -1.453591  0.261520  1
1 -0.131134 -0.058023 -2.350293  1
2  0.706925  0.180733 -1.903122  1
3 -1.298551 -0.499659 -1.293410  0
4  0.922483  1.226597 -1.494647  1
5  0.390577 -1.198977 -0.324572  1
6  0.004753  2.257795 -0.501934  1
7 -0.085302  1.042766  0.352984  1
8 -1.324923 -0.396631 -0.894827  1
9  0.772560  1.146101 -0.390633  1

In [4]:
from sklearn.svm import SVR

In [5]:
from sklearn.tree import DecisionTreeRegressor


In [6]:
X=df.loc[:,["A","B","C"]]
Y=df.loc[:,"D"]

In [7]:
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel

In [8]:
# 过滤思想 -- 相关性去
skb=SelectKBest(k=2)
skb.fit(X.values,Y.values)
print(skb.transform(X.values))
# 保留A.B

[[-0.44152552 -1.45359087]
 [-0.13113368 -0.05802276]
 [ 0.70692478  0.18073328]
 [-1.29855134 -0.49965855]
 [ 0.92248323  1.22659726]
 [ 0.39057685 -1.1989768 ]
 [ 0.00475314  2.25779461]
 [-0.08530223  1.04276572]
 [-1.32492278 -0.39663084]
 [ 0.77255974  1.14610123]]


In [9]:
# 包裹法
rfe=RFE(estimator=SVR(kernel="linear"),n_features_to_select=2,step=1)
print(rfe.fit_transform(X,Y))
# 保留A,C

[[-0.44152552  0.26151966]
 [-0.13113368 -2.35029304]
 [ 0.70692478 -1.90312233]
 [-1.29855134 -1.29340997]
 [ 0.92248323 -1.49464746]
 [ 0.39057685 -0.32457234]
 [ 0.00475314 -0.50193419]
 [-0.08530223  0.3529842 ]
 [-1.32492278 -0.89482725]
 [ 0.77255974 -0.39063338]]


In [11]:
# 嵌入思想 -- 数据量可以使用样本
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.001)
print(sfm.fit_transform(X,Y))
# 保留A,B

[[-0.44152552 -1.45359087]
 [-0.13113368 -0.05802276]
 [ 0.70692478  0.18073328]
 [-1.29855134 -0.49965855]
 [ 0.92248323  1.22659726]
 [ 0.39057685 -1.1989768 ]
 [ 0.00475314  2.25779461]
 [-0.08530223  1.04276572]
 [-1.32492278 -0.39663084]
 [ 0.77255974  1.14610123]]
