# 使用pickle序列化numpy array

In [2]:
import pickle
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
f = open('x.pkl', 'wb')

In [6]:
pickle.dump(x, f)

In [7]:
!ls

Array的input和output.ipynb   数组与矩阵运算.ipynb
x.pkl


In [8]:
f = open('x.pkl', 'rb')

In [9]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.save('one_array', x)

In [11]:
!ls

Array的input和output.ipynb   x.pkl
one_array.npy                数组与矩阵运算.ipynb


In [12]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y = np.arange(20)

In [14]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez('two_array.npz', a=x, b=y)
!ls

Array的input和output.ipynb   x.pkl
one_array.npy                数组与矩阵运算.ipynb
two_array.npz


In [16]:
c = np.load('two_array.npz')

In [17]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])