In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3,3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr2],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
s1 = Series([1,2,3], index=['X','Y','Z'])

In [9]:
s2 = Series([4,5], index=['A','B'])

In [10]:
s1

X    1
Y    2
Z    3
dtype: int64

In [11]:
s2

A    4
B    5
dtype: int64

In [12]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [13]:
pd.concat([s1,s2],axis=1)

/Users/hui/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

In [14]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [15]:
df1

X         Y         Z
0 -0.776545 -0.857427 -1.839585
1 -2.376046 -0.936791  0.466720
2  0.973252 -0.333704  1.695701
3  1.308328  0.106909  0.430595

In [16]:
df2 = DataFrame(np.random.randn(3,3), columns=['X','Y','A'])

In [17]:
df2

X         Y         A
0  1.069496  1.724729 -0.494788
1  1.537868  0.142164  0.672053
2 -0.278067  0.726115  0.450580

In [18]:
pd.concat([df1,df2])

/Users/hui/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A         X         Y         Z
0       NaN -0.776545 -0.857427 -1.839585
1       NaN -2.376046 -0.936791  0.466720
2       NaN  0.973252 -0.333704  1.695701
3       NaN  1.308328  0.106909  0.430595
0 -0.494788  1.069496  1.724729       NaN
1  0.672053  1.537868  0.142164       NaN
2  0.450580 -0.278067  0.726115       NaN

In [19]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

# Combine

In [20]:
s1 = Series([2, np.nan, 4, np.nan], index=['A','B','C','D'])

In [21]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [22]:
s2 = Series([1,2,3,4], index=['A','B','C','D'])

In [23]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [24]:
# s2去填充s1
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [25]:
df1 = DataFrame({
    'X': [1, np.nan, 3, np.nan],
    'Y': [5, np.nan, 7, np.nan],
    'Z': [9, np.nan, 11,np.nan]
})

In [26]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [27]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1,2,3,4]
})

In [28]:
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [29]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0